[package]
name = "combinations"
version = "0.1.0"
authors = ["Meltinglava"]
edition = "2018"
description = "This crate give you all the combinations of values in a vec"
license = "MIT OR Apache-2.0"
repository = "https://github.com/meltinglava/uniquecombinations/"

[dependencies]
